name: Issue Comment Commands

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  handle-start-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/start')
    steps:
      - name: Add debug output
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Organization: ${{ github.repository_owner }}"
      
      - name: Handle start command
        uses: idynic/idynic-github-actions/handle-issue-commands@main
        with:
          command: 'start'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Create branch for issue  
        uses: idynic/idynic-github-actions/create-issue-branch@main
        with:
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Update issue status to In Progress
        uses: idynic/idynic-github-actions/update-issue-status@main
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'In Progress'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: ${{ github.repository_owner }}

  handle-done-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/done')
    steps:
      - name: Handle done command
        uses: idynic/idynic-github-actions/handle-issue-commands@main
        with:
          command: 'done'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Update issue status to Done
        uses: idynic/idynic-github-actions/update-issue-status@main
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'Done'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: ${{ github.repository_owner }}

  handle-review-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/review')
    steps:
      - name: Handle review command
        uses: idynic/idynic-github-actions/handle-issue-commands@main
        with:
          command: 'review'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Update issue status to Waiting for Review
        uses: idynic/idynic-github-actions/update-issue-status@main
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'Waiting for Review'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: ${{ github.repository_owner }}

  handle-close-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/close')
    steps:
      - name: Handle close command
        uses: idynic/idynic-github-actions/handle-issue-commands@main
        with:
          command: 'close'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Close issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });

      - name: Update issue status to Done
        uses: idynic/idynic-github-actions/update-issue-status@main
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'Done'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: ${{ github.repository_owner }}