name: Issue Comment Commands

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  handle-start-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/start')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4
        with:
          repository: idynic/idynic-github-actions
          path: .github/actions
          token: ${{ secrets.PROJECT_TOKEN }}

      - name: Handle start command
        id: handle-start-command
        uses: ./.github/actions/handle-issue-commands
        with:
          command: 'start'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Create branch for issue
        if: steps.handle-start-command.outputs.authorized == 'true' && steps.handle-start-command.outputs.processed == 'true'
        uses: ./.github/actions/create-issue-branch
        with:
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Update issue status to In Progress
        if: steps.handle-start-command.outputs.authorized == 'true' && steps.handle-start-command.outputs.processed == 'true'
        uses: ./.github/actions/update-issue-status
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'In Progress'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: 'idynic'

  handle-done-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/done')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4
        with:
          repository: idynic/idynic-github-actions
          path: .github/actions
          token: ${{ secrets.PROJECT_TOKEN }}

      - name: Handle done command
        id: handle-done-command
        uses: ./.github/actions/handle-issue-commands
        with:
          command: 'done'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Update issue status to Done
        if: steps.handle-done-command.outputs.authorized == 'true' && steps.handle-done-command.outputs.processed == 'true'
        uses: ./.github/actions/update-issue-status
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'Done'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: 'idynic'

  handle-review-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/review')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4
        with:
          repository: idynic/idynic-github-actions
          path: .github/actions
          token: ${{ secrets.PROJECT_TOKEN }}

      - name: Handle review command
        id: handle-review-command
        uses: ./.github/actions/handle-issue-commands
        with:
          command: 'review'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Update issue status to Waiting for Review
        if: steps.handle-review-command.outputs.authorized == 'true' && steps.handle-review-command.outputs.processed == 'true'
        uses: ./.github/actions/update-issue-status
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'Waiting for Review'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: 'idynic'

  handle-close-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/close')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4
        with:
          repository: idynic/idynic-github-actions
          path: .github/actions
          token: ${{ secrets.PROJECT_TOKEN }}

      - name: Handle close command
        id: handle-close-command
        uses: ./.github/actions/handle-issue-commands
        with:
          command: 'close'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Close issue
        if: steps.handle-close-command.outputs.authorized == 'true' && steps.handle-close-command.outputs.processed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });

      - name: Update issue status to Done
        if: steps.handle-close-command.outputs.authorized == 'true' && steps.handle-close-command.outputs.processed == 'true'
        uses: ./.github/actions/update-issue-status
        with:
          issue-number: ${{ github.event.issue.number }}
          status: 'Done'
          token: ${{ secrets.PROJECT_TOKEN }}
          organization: 'idynic'